# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(blank=True, max_length=50, null=True)),
                ('council', models.CharField(blank=True, max_length=20, null=True)),
                ('post_holder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralBodyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('roll_no', models.IntegerField(null=True)),
                ('programme', models.CharField(choices=[('B.Tech', 'B.Tech'), ('B.S', 'B.S'), ('BS-MBA', 'BS-MBA'), ('BS-MS', 'BS-MS'), ('BS-MT', 'BS-MT'), ('BT-M.Des', 'BT-M.Des'), ('BT-MBA', 'BT-MBA'), ('BT-MS', 'BT-MS'), ('Exchng Prog.', 'Exchng Prog.'), ('MBA', 'MBA'), ('MDes', 'MDes'), ('MS-Research', 'MS-Research'), ('MSc(2 yr)', 'MSc(2 yr)'), ('MSc(Int)', 'MSc(Int)'), ('MT(Dual)', 'MT(Dual)'), ('MTech', 'MTech'), ('PGPEX-VLM', 'PGPEX-VLM'), ('PhD', 'PhD'), ('PhD(Dual)', 'PhD(Dual)'), ('Prep.', 'Prep.'), ('SURGE', 'SURGE')], default='B.Tech', max_length=7)),
                ('department', models.CharField(choices=[('Aerospace Engineering', 'AE'), ('Biological Sciences & Engineering', 'BSBE'), ('Chemical Engineering', 'CHE'), ('Civil Engineering', 'CE'), ('Computer Science & Engineering', 'CSE'), ('Electrical Engineering', 'EE'), ('Materials Science & Engineering', 'MSE'), ('Mechanical Engineering', 'ME'), ('Industrial & Management Engineering', 'IME'), ('Chemistry', 'CHM'), ('Mathematics & Scientific Computing', 'MTH'), ('Physics', 'PHY'), ('Earth Sciences', 'ES'), ('Cognitive Sciences', 'Cognitive Sciences'), ('Humanities and Social Sciences', 'HSS'), ('Laser Technology', 'Laser Technology'), ('Photonics Science & Engineering', 'Photonics Science & Engg.'), ('Statistics', 'Statistics')], default='AE', max_length=200)),
                ('hall', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=1, max_length=10)),
                ('room_no', models.CharField(blank=True, max_length=10, null=True)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SenatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('January', 'January'), ('August', 'August')], max_length=10)),
                ('fund', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SenateSeedFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('ssf', models.IntegerField(default=0)),
                ('council', models.CharField(blank=True, max_length=20, null=True)),
                ('entity', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
