# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0002_auto_20170929_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senatepost',
            old_name='fund',
            new_name='max_fund',
        ),
        migrations.AlterField(
            model_name='adminpost',
            name='council',
            field=models.CharField(blank=True, choices=[('Science & Technology Council', 'SnT Council'), ('Films and Cultural Council', 'Films and Cult Council'), ('Sports Council', 'Sports Council'), ('President Student Gymkhana', 'President Student Gymkhana'), ("Chairperson Students' Senate", "Chairperson Students' Senate")], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='senateseedfund',
            name='council',
            field=models.CharField(blank=True, choices=[('Science & Technology Council', 'SnT Council'), ('Films and Cultural Council', 'Films and Cult Council'), ('Sports Council', 'Sports Council'), ('President Student Gymkhana', 'President Student Gymkhana'), ("Chairperson Students' Senate", "Chairperson Students' Senate")], max_length=20, null=True),
        ),
    ]
