# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0003_auto_20170929_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='senateseedfund',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('approval ongoing', 'approval ongoing'), ('approval complete', 'approval complete')], default='in progress', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminpost',
            name='council',
            field=models.CharField(blank=True, choices=[('Science & Technology Council', 'SnT Council'), ('Films and Cultural Council', 'Films and Cult Council'), ('Sports Council', 'Sports Council'), ('President Student Gymkhana', 'President Student Gymkhana'), ("Chairperson Students' Senate", "Chairperson Students' Senate")], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='senateseedfund',
            name='council',
            field=models.CharField(blank=True, choices=[('Science & Technology Council', 'SnT Council'), ('Films and Cultural Council', 'Films and Cult Council'), ('Sports Council', 'Sports Council'), ('President Student Gymkhana', 'President Student Gymkhana'), ("Chairperson Students' Senate", "Chairperson Students' Senate")], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='senateseedfund',
            name='entity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
