# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 21:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ssf', '0004_auto_20170929_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='senateseedfund',
            name='created_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
