# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0005_senateseedfund_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='senateseedfund',
            name='approval',
            field=models.ManyToManyField(blank=True, null=True, related_name='approvals', to='ssf.AdminPost'),
        ),
        migrations.AddField(
            model_name='senateseedfund',
            name='chair_level',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='senateseedfund',
            name='fin_convener',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminpost',
            name='council',
            field=models.CharField(blank=True, choices=[('Science & Technology Council', 'Science & Technology Council'), ('Films and Cultural Council', 'Films and Cultural Council'), ('Sports Council', 'Sports Council'), ('President Student Gymkhana', 'President Student Gymkhana'), ("Chairperson Students' Senate", "Chairperson Students' Senate")], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='senateseedfund',
            name='council',
            field=models.CharField(blank=True, choices=[('Science & Technology Council', 'Science & Technology Council'), ('Films and Cultural Council', 'Films and Cultural Council'), ('Sports Council', 'Sports Council'), ('President Student Gymkhana', 'President Student Gymkhana'), ("Chairperson Students' Senate", "Chairperson Students' Senate")], max_length=50, null=True),
        ),
    ]
