# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0006_auto_20170929_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senateseedfund',
            name='approval',
            field=models.ManyToManyField(blank=True, related_name='approvals', to='ssf.AdminPost'),
        ),
    ]
