# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0008_auto_20170929_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='senateseedfund',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
