# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 09:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ssf', '0011_auto_20171001_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senateseedfund',
            name='created_by',
        ),
        migrations.AddField(
            model_name='senateseedfund',
            name='created_by',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
