# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 09:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ssf', '0012_auto_20171001_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senateseedfund',
            name='created_by',
        ),
        migrations.AddField(
            model_name='senateseedfund',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
