# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0013_auto_20171001_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='senateseedfund',
            name='released',
            field=models.NullBooleanField(default=False),
        ),
    ]
