# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 16:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0016_contribution_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='contributer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
