# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0017_auto_20171001_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='senateseedfund',
            name='reject_message',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='senateseedfund',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('sent to parent', 'sent to parent'), ('sent to chair', 'sent to chair'), ('open for funding', 'open for funding'), ('approval complete', 'approval complete')], default='in progress', max_length=50),
        ),
    ]
