# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0018_auto_20171014_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='senateseedfund',
            name='rejected',
            field=models.NullBooleanField(default=False),
        ),
    ]
