# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 20:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ssf', '0019_senateseedfund_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenatorFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_amount', models.IntegerField(blank=True, null=True)),
                ('pledged', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_left', models.IntegerField(blank=True, default=models.IntegerField(blank=True, null=True), null=True)),
                ('senator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='senatepost',
            name='max_fund',
        ),
        migrations.AlterField(
            model_name='senateseedfund',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('sent to parent', 'sent to parent'), ('sent to chair', 'sent to chair'), ('open for funding', 'open for funding'), ('ssf closed', 'ssf closed'), ('approval complete', 'approval complete')], default='in progress', max_length=50),
        ),
        migrations.AddField(
            model_name='senatepost',
            name='fund',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ssf.SenatorFund'),
        ),
    ]
